name: Example Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello World!
      - name: Run a multi-line script
        run: |
          echo Add other commands you want to run
          echo This runs in a shell
      - name: Run a script
        env:
          TEST_ENV_SECRET: ${{ secrets.TEST_ENV_SECRET }}
          TEST_ENV_VAR: ${{ vars.TEST_ENV_VAR }}
        run: echo "The value of TEST_ENV_SECRET is $TEST_ENV_SECRET and value of TEST_ENV_VAR is $TEST_ENV_VAR"
